name: Go

on:
  push:
    branches: [ master, mcbbs ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        CGO_ENABLED=0 go build -o creditget -trimpath -ldflags "-w -s"
        export PATH=${PATH}:${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin
        CC=aarch64-linux-android21-clang CXX=aarch64-linux-android21-clang++ CGO_ENABLED=1 GOOS=android GOARCH=arm64 go build -o creditget-android -trimpath -ldflags="-s -w"
        ls ${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin
    - name: Test
      run: go test -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       # A file, directory or wildcard pattern that describes what to upload
       path: ./creditget*

    
